services:
  serverh1:
    tty: true
    pull_policy: always
    restart: unless-stopped
    image: registry.stevenlie.my.id/stevenlie14/serverh1:latest
    container_name: serverh1
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - APP_PORT=${APP_PORT}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - DEBUG=${DEBUG}